### ISSUE TITLE
crate status

### ISSUE THREAD

**Issue by Dowwie** [piperRyan/rust-postgres-interval#30]
Would you like a PR to turn this into a rust-postgres compatible library?  I found this library while looking for one.

**Comment by piperRyan** [comment]
Hey, @Dowwie . Long term this project was meant to be a something that can work for both rust-postgres and diesel so the end goal is to have it integrated with both. Unfortunately, I have been really busy so I haven't really fleshed out what I want for 0.0.1 release (before I put it up on crates.io), I am hoping to work on it some more next week, so I am hesitant to say yes at this time to a PR to rust-postgres, but I am hoping in the near future there will be. :) 

However, to answer your question more directly I think the correct choice here is to create a PR in rust-postgres and diesel where the appropriate dependencies are already available to convert the raw data stream into the Interval struct which should work with at least version 3 of the postgres protocol. This being said, if there something specific that I am not addressing in this crate please let me know!

**Comment by Dowwie** [comment]
Diesel already has Interval support.  On the other hand, rust-postgres doesn't.  So, *today* I'm implementing the traits and whatever necessary to make it work.  Some things that I've changed with this project in my fork of it:  I shortened the crate name to pg_interval.  I renamed postgres.rs to pg_interval.rs to avoid naming collision with the postgres crate.  I realize it's a matter of preference but I use lib.rs strictly for managing root imports.  I'd move everything but the imports into a separate module, interval.rs.  Your crate, your choice, though.

**Comment by piperRyan** [comment]
@Dowwie Sorry for not getting back to you sooner. However, there are some suggestions that you have made that I will be implementing or had a plan to  do so already. I just recently merged in a chunk of work that you might want to check out. 

However, I am still hesitant to state that this crate is ready for production/development. However, I will be polling community in the next day or so to see if their are any use cases I am overlooking and hopefully as part of this discussion I will be determining the preferred way to integrating this crate with other ones. 

I be happy review and potentially accept any MR that you have all I ask is that you review my [contributing guidelines](https://github.com/piperRyan/rust-postgres-interval/blob/master/CONTRIBUTING.md) prior to making any submission.

Feel to create a new issue or reopen this one if you have any more comments or questions.
